id: t5-small.0613.b

mode: training

epochs: 2

backbone:
  name: t5-small
  model_max_length: 512

dataset:
  - label: Human
    token: <extra_id_0>
    token_id: 32099
    root: data/split/Human
  - label: ChatGPT
    token: <extra_id_1>
    token_id: 32098
    root: data/split/GPT-4
  - label: Claude
    token: <extra_id_2>
    token_id: 32097
    root: data/split/Claude-Instant-v1
  - label: Gemini
    token: <extra_id_3>
    token_id: 32096
    root: data/split/Gemini-Pro

dataloader:
  batch_size: 16
  num_workers: 4

tokenizer:
  padding: true
  truncation: true
  return_tensors: pt

optimizer:
  lr: 1.0e-4
  weight_decay: 5.0e-5
  batch_size: 128
